### ISSUE TITLE
The reproduced results are inconsistent with the results in the paper

### ISSUE THREAD

**Issue by hduwbf** [microsoft/SwinBERT#5]
Thanks for your contributions.
I have successfully run the inference code and got the results on MSRVTT (B4:41.8, M:29.9, R:62.1, C:54.4).
I found the results were inconsistent with the results in the paper.
I run the code by:
```
EVAL_DIR='./models/table1/msrvtt/best_checkpoint/'
CUDA_VISIBLE_DEVICES=0 python src/tasks/run_caption_VidSwinBert.py \
       --val_yaml MSRVTT-v2/test_32frames.yaml  \
       --do_eval true \
       --do_train false \
       --eval_model_dir $EVAL_DIR
```

Do I need to modify hyperparameters or other settings if I want to reproduce the results in the paper?
Thanks again for your contribution！

**Comment by kevinlin311tw** [comment]
Thanks for the question! I have tried a few more tests on my local machine. But I couldn't reproduce 54.4 CIDEr. So far, my reproduced MSRVTT CIDEr scores are 55.1 on valid split, and 53.8 on test split. 

I observed fluctuations on CIDEr scores when using different input frames (e.g., with different offline pre-extracted 32-frame tsv or 128-frame tsv). I suspect this is one possible reason that causes inconsistent performance. 

Overall, your reproduced results look reasonable to me. I would suggest to reference/compare our latest CIDEr scores reported in our Guthub repo.

**Comment by zsw111-zzz** [comment]
Thanks for your contributions.
when i use valid split,I also got the results on MSRVTT (B4:42.61, M:29.94, R:62.22, C:54.46).
when i use test split,I also got the results on MSRVTT (B4:41.81, M:29.95, R:62.09, C:54.37).
I run the code by:
EVAL_DIR='./models/table1/msrvtt/best-checkpoint/'
CUDA_VISIBLE_DEVICES=0 python src/tasks/run_caption_VidSwinBert.py \
       --val_yaml MSRVTT-v2/val.yaml  --do_eval true --do_train false --eval_model_dir $EVAL_DIR

EVAL_DIR='./models/table1/msrvtt/best-checkpoint/'
CUDA_VISIBLE_DEVICES=0 python src/tasks/run_caption_VidSwinBert.py \
       --val_yaml MSRVTT-v2/test.yaml  --do_eval true --do_train false --eval_model_dir $EVAL_DIR

maybe the problem is about the difference between the test.yaml and test_32frames.yaml,i have test.img.tsv so i can use the test.yaml but i can't use the test_32frames.yaml,because i don't have frame_tsv/test_32frames.img.tsv and i don't have test_32frames.img.lineidx ,the frame_tsv/test_32frames.img.tsv is not in https://datarelease.blob.core.windows.net/swinbert/datasets/MSRVTT-v2.zip,I don't know if the test_32frames.img.tsv is the same as the test.img.tsv,maybe the author can share test_32frames.img.tsv,test_32frames.img.lineidx,val_32frames.img.tsv,val_32frames.img.lineidx

**Comment by zsw111-zzz** [comment]
Thanks for your contributions.
when i use valid split,I also got the results on MSRVTT (B4:42.61, M:29.94, R:62.22, C:54.46).
when i use test split,I also got the results on MSRVTT (B4:41.81, M:29.95, R:62.09, C:54.37).
I run the code by:
EVAL_DIR='./models/table1/msrvtt/best-checkpoint/'
CUDA_VISIBLE_DEVICES=0 python src/tasks/run_caption_VidSwinBert.py
--val_yaml MSRVTT-v2/val.yaml --do_eval true --do_train false --eval_model_dir $EVAL_DIR

EVAL_DIR='./models/table1/msrvtt/best-checkpoint/'
CUDA_VISIBLE_DEVICES=0 python src/tasks/run_caption_VidSwinBert.py
--val_yaml MSRVTT-v2/test.yaml --do_eval true --do_train false --eval_model_dir $EVAL_DIR

maybe the problem is about the difference between the test.yaml and test_32frames.yaml,i have test.img.tsv so i can use the test.yaml but i can't use the test_32frames.yaml,because i don't have frame_tsv/test_32frames.img.tsv and i don't have test_32frames.img.lineidx ,the frame_tsv/test_32frames.img.tsv is not in https://datarelease.blob.core.windows.net/swinbert/datasets/MSRVTT-v2.zip,I don't know if the test_32frames.img.tsv is the same as the test.img.tsv,maybe the author can share test_32frames.img.tsv,test_32frames.img.lineidx,val_32frames.img.tsv,val_32frames.img.lineidx

Thanks again for your contribution！

**Comment by zsw111-zzz** [comment]
Thanks for your contributions.
when i use valid split,I also got the results on MSRVTT (B4:42.61, M:29.94, R:62.22, C:54.46).
when i use test split,I also got the results on MSRVTT (B4:41.81, M:29.95, R:62.09, C:54.37).
I run the code by:
EVAL_DIR='./models/table1/msrvtt/best-checkpoint/'
CUDA_VISIBLE_DEVICES=0 python src/tasks/run_caption_VidSwinBert.py
--val_yaml MSRVTT-v2/val.yaml --do_eval true --do_train false --eval_model_dir $EVAL_DIR

EVAL_DIR='./models/table1/msrvtt/best-checkpoint/'
CUDA_VISIBLE_DEVICES=0 python src/tasks/run_caption_VidSwinBert.py
--val_yaml MSRVTT-v2/test.yaml --do_eval true --do_train false --eval_model_dir $EVAL_DIR

maybe the problem is about the difference between the test.yaml and test_32frames.yaml,i don't know if the test_32frames.img.tsv is the same as the test.img.tsv,and how can i get test_32frames.img.tsv,test_32frames.img.lineidx,val_32frames.img.tsv,val_32frames.img.lineidx?

Thanks again for your contribution！

**Comment by kevinlin311tw** [comment]
Agree. The problem could be the difference between input yaml files. For some reason, you got slightly better results than mine. I guess this is probably because I didn't successfully download all the MSRVTT video files. 

Unfortunately, due to copyright issues, we cannot share the raw video files and the raw frames. Since the tsv files (test_32frames.img.tsv and test_128frames.img.tsv) store the video frames, we couldn't release the tsv files you mentioned above. 

I plan to prepare a frame-based TSV generation tutorial, so you could generate the files. Please stay tuned.

**Comment by zsw111-zzz** [comment]
Thanks!

**Comment by hduwbf** [comment]
Thanks for your reply!
